In [16]:
import pandas as pd
from sqlalchemy import create_engine
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [3]:
engine = create_engine(
    "postgresql+psycopg2://stephensefa@localhost:5432/churn_project"
)

In [4]:
query = """
SELECT *
FROM customers;
"""

df = pd.read_sql(query, engine)

df.head()

,customerid,gender,seniorcitizen,partner,dependents,tenure,phoneservice,multiplelines,internetservice,onlinesecurity,...,deviceprotection,techsupport,streamingtv,streamingmovies,contract,paperlessbilling,paymentmethod,monthlycharges,totalcharges,churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerid        7043 non-null   object
 1   gender            7043 non-null   object
 2   seniorcitizen     7043 non-null   int64
 3   partner           7043 non-null   object
 4   dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   phoneservice      7043 non-null   object
 7   multiplelines     7043 non-null   object
 8   internetservice   7043 non-null   object
 9   onlinesecurity    7043 non-null   object
 10  onlinebackup      7043 non-null   object
 11  deviceprotection  7043 non-null   object
 12  techsupport       7043 non-null   object
 13  streamingtv       7043 non-null   object
 14  streamingmovies   7043 non-null   object
 15  contract          7043 non-null   object
 16  paperlessbilling  7043 non-null   object
 17  paymentmethod     7043 non-null   object
 18  monthlycharges    7043 non-null   float64
 19  totalcharges      7043 non-null   object
 20  churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [6]:
df.describe()

       seniorcitizen       tenure  monthlycharges
count    7043.000000  7043.000000     7043.000000
mean        0.162147    32.371149       64.761692
std         0.368612    24.559481       30.090047
min         0.000000     0.000000       18.250000
25%         0.000000     9.000000       35.500000
50%         0.000000    29.000000       70.350000
75%         0.000000    55.000000       89.850000
max         1.000000    72.000000      118.750000

In [7]:
df["churn"].value_counts()

churn
No     5174
Yes    1869
Name: count, dtype: int64

In [8]:
df["totalcharges"] = pd.to_numeric(
    df["totalcharges"],
    errors="coerce"
)

df = df.dropna()

In [9]:
df["churn"] = df["churn"].map({
    "Yes": 1,
    "No": 0
})

In [10]:
df = df.drop("customerid", axis=1)

In [11]:
df_encoded = pd.get_dummies(
    df,
    drop_first=True
)

In [12]:
print(df_encoded.head())

   seniorcitizen  tenure  monthlycharges  totalcharges  churn  gender_Male  \
0              0       1           29.85         29.85      0        False
1              0      34           56.95       1889.50      0         True
2              0       2           53.85        108.15      1         True
3              0      45           42.30       1840.75      0         True
4              0       2           70.70        151.65      1        False

   partner_Yes  dependents_Yes  phoneservice_Yes  \
0         True           False             False
1        False           False              True
2        False           False              True
3        False           False             False
4        False           False              True

   multiplelines_No phone service  ...  streamingtv_No internet service  \
0                            True  ...                            False
1                           False  ...                            False
2                           False  ...                            False
3                            True  ...                            False
4                           False  ...                            False

   streamingtv_Yes  streamingmovies_No internet service  streamingmovies_Yes  \
0            False                                False                False
1            False                                False                False
2            False                                False                False
3            False                                False                False
4            False                                False                False

   contract_One year  contract_Two year  paperlessbilling_Yes  \
0              False              False                  True
1               True              False                 False
2              False              False                  True
3               True              False                 False
4              False              False                  True

   paymentmethod_Credit card (automatic)  paymentmethod_Electronic check  \
0                                  False                            True
1                                  False                           False
2                                  False                           False
3                                  False                           False
4                                  False                            True

   paymentmethod_Mailed check
0                       False
1                        True
2                        True
3                       False
4                       False

[5 rows x 31 columns]

In [13]:
X = df_encoded.drop("churn", axis=1)
y = df_encoded["churn"]

In [15]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [17]:
model = LogisticRegression(max_iter=1000)

model.fit(X_train, y_train)

/Users/stephensefa/anaconda3/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(max_iter=1000)

In [18]:
y_pred = model.predict(X_test)

In [19]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report
)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall:", recall_score(y_test, y_pred))
print("F1 Score:", f1_score(y_test, y_pred))

Accuracy: 0.8073916133617626
Precision: 0.6594427244582043
Recall: 0.56951871657754
F1 Score: 0.6111908177905309

In [20]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.85      0.89      0.87      1033
           1       0.66      0.57      0.61       374

    accuracy                           0.81      1407
   macro avg       0.76      0.73      0.74      1407
weighted avg       0.80      0.81      0.80      1407

In [21]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.85      0.89      0.87      1033
           1       0.66      0.57      0.61       374

    accuracy                           0.81      1407
   macro avg       0.76      0.73      0.74      1407
weighted avg       0.80      0.81      0.80      1407

In [22]:
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42,
    class_weight="balanced"
)

rf_model.fit(X_train, y_train)

RandomForestClassifier(class_weight='balanced', random_state=42)

In [23]:
rf_pred = rf_model.predict(X_test)

In [24]:
print(classification_report(y_test, rf_pred))

              precision    recall  f1-score   support

           0       0.83      0.90      0.86      1033
           1       0.64      0.49      0.56       374

    accuracy                           0.79      1407
   macro avg       0.74      0.70      0.71      1407
weighted avg       0.78      0.79      0.78      1407

In [26]:
importance = pd.DataFrame({
    "feature": X.columns,
    "importance": rf_model.feature_importances_
})

importance = importance.sort_values(
    "importance",
    ascending=False
)

print(importance.head(5))

                        feature  importance
3                  totalcharges    0.175739
1                        tenure    0.169785
2                monthlycharges    0.151681
25            contract_Two year    0.056537
10  internetservice_Fiber optic    0.039186

In [28]:
importance = pd.DataFrame({
    "feature": X.columns,
    "importance": rf_model.feature_importances_
})

importance = importance.sort_values(
    "importance",
    ascending=False
)

print(importance.head(5))

                        feature  importance
3                  totalcharges    0.175739
1                        tenure    0.169785
2                monthlycharges    0.151681
25            contract_Two year    0.056537
10  internetservice_Fiber optic    0.039186